version: '2'
services:
  seed:
    image: "diegopacheco/akka-2-5-6-cluster-docker:1.0"
    hostname: "akkaseed"
    command: "-Dakka.remote.netty.tcp.hostname=akkaseed"

  node:
    image: "diegopacheco/akka-2-5-6-cluster-docker:1.0"
    links: ["seed:akkaseed"]
