version: '2'
services:
  seed:
    image: diegopacheco/akka-2-5-6-cluster-docker:1.0
    ports:
      - '1600:1600'
    environment:
      CLUSTER_PORT: 1600
      CLUSTER_IP: seed
      SEED_PORT_1600_TCP_ADDR: seed
  c1:
    image: diegopacheco/akka-2-5-6-cluster-docker:1.0
    ports:
      - '1601:1601'
    environment:
      CLUSTER_PORT: 1601
      CLUSTER_IP: c1
      SEED_PORT_1600_TCP_ADDR: seed
  c2:
    image: diegopacheco/akka-2-5-6-cluster-docker:1.0
    ports:
      - '1602:1602'
    environment:
      CLUSTER_PORT: 1602
      CLUSTER_IP: c2
      SEED_PORT_1600_TCP_ADDR: seed
  c3:
    image: diegopacheco/akka-2-5-6-cluster-docker:1.0
    environment:
      CLUSTER_PORT: 0
      CLUSTER_IP: "127.0.0.1"
      SEED_PORT_1600_TCP_ADDR: seed
