# --- !Ups

CREATE TABLE CatOwner (CAT_ID INT NOT NULL, OWNER_ID INT NOT NULL,PRIMARY KEY ( CAT_ID, OWNER_ID ) );

INSERT INTO CatOwner (CAT_ID,OWNER_ID) VALUES (1,1);
INSERT INTO CatOwner (CAT_ID,OWNER_ID) VALUES (2,1);
INSERT INTO CatOwner (CAT_ID,OWNER_ID) VALUES (4,2);

# --- !Downs

# drop table "CatOwner";
