apiVersion: apps/v1
kind: Deployment
metadata:
  name: fast-endpoints
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fast-endpoints
  template:
    metadata:
      labels:
        app: fast-endpoints
    spec:
      containers:
      - name: fast-endpoints
        image: localhost/fast-endpoints:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8081
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://postgres:5432/appdb
        - name: SPRING_DATASOURCE_USERNAME
          value: postgres
        - name: SPRING_DATASOURCE_PASSWORD
          value: postgres
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8081
          initialDelaySeconds: 30
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8081
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: fast-endpoints
  namespace: default
spec:
  selector:
    app: fast-endpoints
  ports:
  - port: 8081
    targetPort: 8081
    nodePort: 30081
  type: NodePort
