apiVersion: apps/v1
kind: Deployment
metadata:
  name: health-checker
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: health-checker
  template:
    metadata:
      labels:
        app: health-checker
    spec:
      containers:
      - name: health-checker
        image: localhost/health-checker:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8083
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8083
          initialDelaySeconds: 20
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8083
          initialDelaySeconds: 40
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: health-checker
  namespace: default
spec:
  selector:
    app: health-checker
  ports:
  - port: 8083
    targetPort: 8083
    nodePort: 30083
  type: NodePort
