create table IF NOT EXISTS PRODUCTS (ID INTEGER NOT NULL,NAME VARCHAR NOT NULL,STOCK INTEGER NOT NULL);
create table IF NOT EXISTS SALES (ID INTEGER NOT NULL,DATE DATE NOT NULL,PRODUCT_ID INTEGER NOT NULL,QUANTITY INTEGER NOT NULL);

insert into PRODUCTS (ID, NAME, STOCK) values (1, 'coke', 10);
insert into PRODUCTS (ID, NAME, STOCK) values (2, 'pepsi', 20);
insert into PRODUCTS (ID, NAME, STOCK) values (3, 'fanta', 30);

insert into SALES (ID, DATE, PRODUCT_ID, QUANTITY) values (1, '2024-12-12', 2, 1);